apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ais.fullname" . }}-secrets
  labels:
    {{- include "ais.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.hmacSecret }}
  hmac-secret: {{ .Values.secrets.hmacSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.apiKey }}
  api-key: {{ .Values.secrets.apiKey | b64enc | quote }}
  {{- end }}
